### ISSUE TITLE
Per Split Results on the Breakfast Dataset

### ISSUE THREAD

**Issue by yassersouri** [ZheLi2020/TimestampActionSeg#1]
In Table 1 of the paper you have provided the comparisons to baselines (naive, uniform and full-supervision) averaged over the 4 splits of the Breakfast dataset.
Can you provide the same metrics per-split?
I only need them for the Breakfast dataset for the following approaches and baselines:
 - Naive
 - Uniform
 - Full-Supervision
 - Your full method

Thank you in advance.

**Comment by ZheLi2020** [comment]
Thank you for your interest. I sent the results to your Gmail email account which is shown on your homepage of Github.

**Comment by yassersouri** [comment]
Thank you very much.

It seems I have not received it. Can you send it again?

**Comment by ZheLi2020** [comment]
Can you please check the spam. If you still don't see it, can you please send an email to my email in paper, I will reply you with the results tomorrow.
