### ISSUE TITLE
On the publicly released annotations

### ISSUE THREAD

**Issue by guuzaa** [ZheLi2020/TimestampActionSeg#2]
Hi @ZheLi2020 ,
 I wonder how you get the released annotations of the GTEA, Breakfast and 50Salads datasets. Which kind of frames did you select? Start, center or random ? 
 Thanks for your work.

**Comment by ZheLi2020** [comment]
We randomly choose the frame as the timestamp. We also tried the start, end, and center in the appendix of this paper. You can read the corresponding paper of datasets to see how they annotated the full-on ground truth.
