### ISSUE TITLE
data problem

### ISSUE THREAD

**Issue by tyler8812** [ZheLi2020/TimestampActionSeg#3]
hi @ZheLi2020 ,
I have a stupid question, where can I get the breakfast/mapping.txt?

Because I can't download the data from the link you gave.
So, I download the I3D feature for breakfast data from [here](https://serre-lab.clps.brown.edu/resource/breakfast-actions-dataset/#Downloads).
Will that be a problem?

**Comment by ZheLi2020** [comment]
Hi @tyler8812 ,

I just tried the link and I can download the data smoothly. Unfortunately, the "mapping.txt" is in the data.
The I3D feature is very slightly different. I think it's no problem you want to try it from the homepage, just design your own mapping.
